  var num1 = math.int(prompt("Pick a number"))
  var num2 = math.int(prompt("Pick another number"))
  var sign = math.int(prompt("Choose to multiply (*), add (+), divide (/) or minus (-)"))
  var product = math.sum(num1 + sign + num2)
  alert (num1 + " " + sign + " " + num2 + " " + "=" + " " + product)
